apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deploy
  labels:
    app: bankapp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp-app
  template:
    metadata:
      labels:
        app: bankapp-app
    spec:
      containers:
      - name: bankapp-container
        image: yuvarajuvemala/bankapp-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-np-service
  labels:
    app: bankapp-app
spec:
  selector:
    app: bankapp-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
